version: '3'

services:
  postgres_telegram_bot:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: telegram_bot
    volumes:
      - ./postgres/data:/var/lib/postgres/data
    ports:
      - '5432:5432'